### ISSUE TITLE
_validate_tuplets frequently errors

### ISSUE THREAD

**Issue by GregoryREvans** [Abjad/abjad-ext-rmakers#24] opened 2019-10-02 19:13 UTC
`_validate_tuplets` frequently returns errors. This is inconvenient if the composer prefers a non-normalized tuplet multiplier. Perhaps this can be removed or possibly altered to something like the following:
```python
def _validate_tuplets(self, selections):
    for tuplet in abjad.iterate(selections).components(abjad.Tuplet):
        if tuplet.multiplier.normalized() is False:
            tuplet.normalize_multiplier()
```
so that the multipliers are automatically normalized rather than sending assertion errors, unless it is very important that only normalized multipliers are produced by the rmakers.

**Comment by trevorbaca** [comment] 2019-10-02 20:50
Hey @GregoryREvans can you add a (small) working example so I can see where that method's erroring?

**Comment by GregoryREvans** [comment] 2019-10-02 21:23
@trevorbaca For instance:
```python
import abjad
import abjadext.rmakers

rmaker_one = abjadext.rmakers.stack(
    abjadext.rmakers.talea(
    [3], 16, extra_counts=[-1, ]
    ),
)
durations = [(1, 8), ]
rmaker_one(durations)
```
gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/evansdsg2/abjad-ext-rmakers/abjadext/rmakers/stack.py", line 115, in __call__
    selection = self.maker(divisions, previous_state=previous_state)
  File "/Users/evansdsg2/abjad-ext-rmakers/abjadext/rmakers/makers.py", line 70, in __call__
    self._validate_tuplets(music_voice) #comment this out?
  File "/Users/evansdsg2/abjad-ext-rmakers/abjadext/rmakers/makers.py", line 249, in _validate_tuplets
    assert tuplet.multiplier.normalized(), repr(tuplet)
AssertionError: Tuplet(Multiplier(2, 1), "c'16")
```
to me, it looks like non-normalized multipliers are produced by particularly small durations.

**Comment by trevorbaca** [comment] 2019-10-03 14:11
Ok cool that's what I was looking for. Just outta curiosity, in that example do you want to leave the 2:1 ratio? Or were you thinking that you were going to normalize the output to just a vanilla eighth note later during rhythm construction?

**Comment by GregoryREvans** [comment] 2019-10-03 14:37
I usually try to normalize/trivialize all my tuplets after rhythm creation.

**Comment by trevorbaca** [comment] 2019-10-03 14:47
Ok, that makes me think that maybe the problem is that `rmakers.TaleaRhythmMaker` shouldn't be producing nonnormalized output. (The cases where `rmakers.TaleaRhythmMaker` produces nonnormalized output all arise when `extra_counts` includes a negative numbers, like -1 in the example we're working with here.)

I just committed a 2-line change that teaches `rmakers.TaleaRhythmMaker` to normalize all of its output. This leaves `_validate_tuplets()` in place, which I think may be the right way to go! In fact, thinking back on it, I think I inserted `_validate_tuplets()` to cause exactly these sorts of discussions to happen.

Can you pull my 2-line change and rerurn all of your scores? I think this might be what we're looking for.

**Comment by GregoryREvans** [comment] 2019-10-03 23:24
Thanks. Seems alright to me so far. I only have two scores using the updated rmakers and they run just fine. I haven't updated my other scores to reflect these updates yet.

**Closed** 2023-02-25 19:38 UTC
